### ISSUE TITLE
clean doesn't work

### ISSUE THREAD

**Issue by basilgood** [faerryn/user.nvim#1]
> The last update broke everything!

Hi!
On the hole the plugin manager works very well.
Only require("user").clean() doesn't.
It not clean deleted plugins. (not uninstall).
But otherwise it's simple and nvim it's opening faster compared with packer and paq.
I don't know why... :).
I ask if it has the possibility to choose a branch or a commit for a certain plugin
and if it has hooks after install (run = ':TSUpdate') ?

**Comment by faerryn** [comment]
Can you share your vimrc (remove any private info from it, of course!).
That way I can debug the issue.

**Comment by basilgood** [comment]
It actually works.
I was fooled by the fact that it clones by the name of the maintainer and not by the name of the plugin.
But after ```lua require'user'.clean()``` the corresponding dir is empty.
The uninstalled plugins directories remain empty.
It's ok.

Remain the question about to choose a branch and hooks.
And I noticed that some plugins are not loaded and require an additional packload.
You want me to open a new issue for that ?

**Comment by faerryn** [comment]
yes, please make two new issues
