### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by Kapelianovych** [faerryn/user.nvim#10]
Hi! I am trying to install the package manager, but I cannot figure out where should I put the bootstrapping code. I am familiar a little only with the default NeoVim's package manager. Thank you in advance!

**Comment by faerryn** [comment]
If you are on linux, then you can put the code in `~/.config/nvim/init.lua` if you don't already have a vimrc.

If you do have a neovim vimrc, then you can put the code in heredocs.

I updated the README to put the example front and center.

**Comment by Kapelianovych** [comment]
Thanks. Is the `~/.local/share/nvim/site/pack/user.nvim/start/user.nvim` directory the right place to clone the repository into?

**Comment by faerryn** [comment]
The repo should be cloned into
`~/.local/share/nvim/site/pack/user/opt/faerryn/user.nvim/default/default/default/default`.

**Comment by Kapelianovych** [comment]
Thanks. All is working fine now.
