### ISSUE TITLE
Some plugins are not loaded

### ISSUE THREAD

**Issue by basilgood** [faerryn/user.nvim#3]
Minimal init.lua:
```
vim.o.swapfile = false
vim.o.undofile = true
vim.bo.swapfile = false
vim.bo.undofile = true
vim.wo.number = true
vim.o.mouse = 'a'
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.bo.tabstop = 2
vim.bo.shiftwidth = 2
vim.bo.expandtab = true
vim.o.list = true
vim.wo.list = true
vim.o.completeopt = "menuone,noinsert"
vim.o.confirm = true
vim.o.hidden = true
vim.o.inccommand = "nosplit"

local user_install_path = vim.fn.stdpath("data").."/site/pack/user/opt/faerryn/user.nvim"
if vim.fn.empty(vim.fn.glob(user_install_path)) > 0 then
  os.execute([[git clone --depth 1 https://github.com/faerryn/user.nvim.git ']]..user_install_path..[[']])
end
vim.api.nvim_command("packadd faerryn/user.nvim")

local user = require"user"
user.setup()
local use = user.use

use "faerryn/user.nvim"

use "tpope/vim-vinegar"
use {
  "hrsh7th/nvim-compe",
  init = function()
    vim.cmd 'packadd hrsh7th/nvim-compe'
  end,
  config = function()
    require'compe'.setup {
      enabled = true;
      autocomplete = true;
      debug = false;
      min_length = 1;
      preselect = 'disable';
      throttle_time = 80;
      source_timeout = 200;
      incomplete_delay = 400;
      max_abbr_width = 100;
      max_kind_width = 100;
      max_menu_width = 100;
      documentation = true;
      source = {
        path = true;
        buffer = true;
      };
    }
  end
}
```
In this case nvim-compe it's not loaded without a new ```vim.cmd 'packadd hrsh7th/nvim-compe'```.
If ```rm -r ~/.local/share/nvim/site/pack/user/``` and start nvim:
```Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/hrsh7th/nvim-compe"```
It doesn't clone repo because of this error. It needs to put ```vim.cmd 'packadd hrsh7th/nvim-compe'```
after the plugin is cloned. If I put it in ```config function()...end``` it doesn't load the plugin.
Some plugins doesn't behave well in opt folder and maybe it's required to have option to
put it in the start folder.
Some plugins only consist of an autoload folder and in this case to put it in opt folder it's useless.
I like your plugin manager very much but I would like to have a little more tweak possibilities.

**Comment by faerryn** [comment]
Can I add your config as a test case under tests/?

**Comment by basilgood** [comment]
Yes please.

**Comment by faerryn** [comment]
Looks like we need to source the after/* directory ourselves
vim/vim#1994

**Comment by basilgood** [comment]
nvim-compe works now.
Thank you for this compromise because it wasn't the plugin manager issue.
This line of code is absolutely necessary?
```print(pack.name.." uses the /after/ directory, which is not intended as per vim#1994. Please contact your plugin author.")```
Each user of this plugin manager will see that message when the editor opens.
compe is probably number one in popularity.

**Comment by faerryn** [comment]
Sounds good.
